# Site
name: "Huisbouwers"
title: "Huisbouwers"
description: "Huisbouwers!"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: 'https://huisbouwers.nl/'
google_analytics: 'G-0G1WXCRRT9'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: lise@ariensvanels.nl

# Authors
authors:
  lise:
    name: Lise
    display_name: Lise    
    avatar: 'assets/images/avatar_lise.png'
    email: lise@ariensvanels.nl
    web: https://huisbouwers.nl/
    description: "is the best"
  maarten:
    name: Maarten
    display_name: Maarten    
    avatar: 'assets/images/avatar.png'
    email: maarten@ariensvanels.nl
    web: https://huisbouwers.nl/
    description: "is the best"    
  
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
